# Generated by Django 4.0.4 on 2022-05-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
