# Generated by Django 4.0.4 on 2022-05-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0007_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
