# Generated by Django 4.0.4 on 2022-05-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0011_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
