# Generated by Django 4.0.4 on 2022-05-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0012_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
    ]
