# Generated by Django 4.0.4 on 2022-05-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0013_alter_doctor_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
