# Generated by Django 4.0.4 on 2022-05-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0015_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
