# Generated by Django 4.0.4 on 2022-05-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0021_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='login',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
