# Generated by Django 4.0.4 on 2022-05-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0008_delete_patient'),
        ('doctorsApp', '0022_remove_doctor_login_remove_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
