# Generated by Django 4.0.4 on 2022-05-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0025_department_hospital_doctor_department_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'diagnostic_methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_type_id', models.IntegerField()),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'diagnostics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('diagnostic_method_id', models.IntegerField()),
            ],
            options={
                'db_table': 'diagnostic_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'examinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExaminationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'examination_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'surveys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'survey_types',
                'managed': False,
            },
        ),
    ]
