# Generated by Django 4.0.4 on 2022-05-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0026_diagnosticmethods_diagnostics_diagnostictypes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticMethods',
        ),
        migrations.DeleteModel(
            name='Diagnostics',
        ),
        migrations.DeleteModel(
            name='DiagnosticTypes',
        ),
        migrations.DeleteModel(
            name='Examinations',
        ),
        migrations.DeleteModel(
            name='ExaminationTypes',
        ),
        migrations.DeleteModel(
            name='Surveys',
        ),
        migrations.DeleteModel(
            name='SurveyTypes',
        ),
    ]
