# Generated by Django 4.0.4 on 2022-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0029_delete_diagnostic_delete_diagnosticmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
