# Generated by Django 4.0.4 on 2022-05-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0037_delete_diagnostic_delete_diagnostictype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('diagnostic_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.diagnosticmethod')),
            ],
        ),
    ]
