# Generated by Django 4.0.4 on 2022-05-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0018_remove_patientsapplications_user_and_more'),
        ('doctorsApp', '0038_diagnostictype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('diagnostic_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.diagnostictype')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsApp.patient')),
            ],
        ),
    ]
