# Generated by Django 4.0.4 on 2022-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0039_diagnostic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='diagnostic_type_id',
            new_name='diagnostic_type',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='diagnostictype',
            old_name='diagnostic_method_id',
            new_name='diagnostic_method',
        ),
        migrations.RenameField(
            model_name='examination',
            old_name='Examination_type_id',
            new_name='Examination_type',
        ),
        migrations.RenameField(
            model_name='examination',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='examination',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
