# Generated by Django 4.0.4 on 2022-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0040_rename_diagnostic_type_id_diagnostic_diagnostic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
