# Generated by Django 4.0.4 on 2022-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0042_survey_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_consulting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
