# Generated by Django 4.0.4 on 2022-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('etrap', models.TextField()),
                ('hospital_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('work_address', models.TextField()),
                ('work', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
    ]
