# Generated by Django 4.0.4 on 2022-05-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
