# Generated by Django 4.0.4 on 2022-05-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorsApp', '0021_doctor'),
        ('patientsApp', '0002_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('etrap', models.TextField()),
                ('work_address', models.TextField()),
                ('work', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.hospital')),
            ],
        ),
    ]
