# Generated by Django 4.0.4 on 2022-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0004_remove_patient_login_remove_patient_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
