# Generated by Django 4.0.4 on 2022-05-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0022_remove_doctor_login_remove_doctor_name_and_more'),
        ('patientsApp', '0007_remove_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.hospital'),
        ),
    ]
