# Generated by Django 4.0.4 on 2022-05-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0007_remove_patient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
