# Generated by Django 4.0.4 on 2022-05-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0025_department_hospital_doctor_department_hospital'),
        ('patientsApp', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsapplications',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.doctor'),
        ),
        migrations.AlterField(
            model_name='patientsapplications',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorsApp.hospital'),
        ),
    ]
