# Generated by Django 4.0.4 on 2022-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0008_alter_patient_doctor_alter_patient_hospital'),
        ('patientsApp', '0010_alter_patientsapplications_doctor_and_more'),
    ]

    operations = [
    ]
