# Generated by Django 4.0.4 on 2022-05-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0011_merge_20220513_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientsApplications',
        ),
    ]
