# Generated by Django 4.0.4 on 2022-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0012_alter_patientsapplications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsapplications',
            options={},
        ),
    ]
