# Generated by Django 4.0.4 on 2022-05-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0013_alter_patientsapplications_options'),
        ('patientsApp', '0013_patientsapplications'),
    ]

    operations = [
    ]
